# Generated by Django 5.2.1 on 2025-05-29 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(help_text='Auto-generated from name', max_length=120, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(help_text='Auto-generated from name', max_length=220, unique=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('thc_content', models.DecimalField(blank=True, decimal_places=2, help_text='THC percentage (e.g., 21.50)', max_digits=5, null=True)),
                ('cbd_content', models.DecimalField(blank=True, decimal_places=2, help_text='CBD percentage (e.g., 0.50)', max_digits=5, null=True)),
                ('flower_type', models.CharField(blank=True, choices=[('Indica', 'Indica'), ('Sativa', 'Sativa'), ('Hybrid', 'Hybrid'), ('High CBD', 'High CBD')], max_length=20, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='kiosk.category')),
            ],
        ),
    ]
