# Generated by Django 5.2.1 on 2025-05-30 00:21

import django.db.models.deletion
import kiosk.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(default=kiosk.utils.generate_order_number, editable=False, max_length=20, unique=True)),
                ('session_key', models.CharField(blank=True, editable=False, help_text='Links to Django session if user is not authenticated', max_length=40, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Submitted', 'Submitted'), ('Paid', 'Paid'), ('Ready', 'Ready'), ('Completed', 'Completed')], default='Pending', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0.06, help_text='Default tax rate, e.g., 0.06 for 6%', max_digits=4)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price_at_purchase', models.DecimalField(decimal_places=2, help_text='Price of the product when this item was added to the cart', max_digits=8)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='kiosk.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kiosk.product')),
            ],
        ),
    ]
