# Generated by Django 5.2.1 on 2025-05-30 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0002_order_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('discount_type', models.CharField(choices=[('Percentage', 'Percentage'), ('Fixed Amount', 'Fixed Amount Off Product'), ('Fixed Amount Off Total', 'Fixed Amount Off Total Cart')], max_length=30)),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Percentage (e.g., 10 for 10%) or fixed amount.', max_digits=10)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('minimum_spend', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum cart subtotal for offer to apply.', max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicable_categories', models.ManyToManyField(blank=True, help_text='Leave blank if offer applies to specific products or entire order.', to='kiosk.category')),
                ('applicable_products', models.ManyToManyField(blank=True, help_text='Leave blank if offer applies to categories or entire order.', to='kiosk.product')),
            ],
        ),
    ]
