# Generated by Django 5.2.1 on 2025-05-31 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0003_specialoffer'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='emoji',
            field=models.CharField(blank=True, help_text='Emoji icon for this category (e.g., 🌿, 🍫, 💨)', max_length=10, null=True),
        ),
    ]
