# Generated by Django 4.2 on 2025-06-11 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0004_category_emoji'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total discount amount applied to this order', max_digits=10),
        ),
    ]
