# Generated by Django 4.2 on 2025-06-11 18:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0005_order_discount_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudtenderCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('kiosk_id', models.CharField(default='Main_Entrance_Kiosk', help_text='Identifier for the kiosk making the call', max_length=100)),
                ('session_id', models.CharField(blank=True, help_text='Customer session ID for tracking', max_length=100)),
                ('reason', models.CharField(choices=[('product_help', 'Product Information & Recommendations'), ('dosage_help', 'Dosage & Consumption Guidance'), ('technical_issue', 'Kiosk Technical Issue'), ('payment_issue', 'Payment Problem'), ('general_help', 'General Assistance'), ('emergency', 'Emergency Assistance')], default='general_help', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low Priority'), ('normal', 'Normal Priority'), ('high', 'High Priority'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending Response'), ('acknowledged', 'Acknowledged by Budtender'), ('in_progress', 'Assistance in Progress'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='pending', max_length=15)),
                ('customer_message', models.TextField(blank=True, help_text='Additional message from customer')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('response_time', models.DurationField(blank=True, help_text='Time taken to acknowledge the call', null=True)),
                ('total_resolution_time', models.DurationField(blank=True, help_text='Total time to resolve the issue', null=True)),
                ('budtender_notes', models.TextField(blank=True, help_text='Internal notes from budtender')),
                ('resolved_by', models.CharField(blank=True, help_text='Staff member who resolved the call', max_length=100)),
            ],
            options={
                'verbose_name': 'Budtender Call',
                'verbose_name_plural': 'Budtender Calls',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BudtenderCallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Call Created'), ('acknowledged', 'Call Acknowledged'), ('in_progress', 'Assistance Started'), ('resolved', 'Call Resolved'), ('dismissed', 'Call Dismissed'), ('note_added', 'Note Added')], max_length=20)),
                ('staff_member', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='kiosk.budtendercall')),
            ],
            options={
                'verbose_name': 'Budtender Call Log',
                'verbose_name_plural': 'Budtender Call Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='budtendercall',
            index=models.Index(fields=['status', 'priority'], name='kiosk_budte_status_5d3ef5_idx'),
        ),
        migrations.AddIndex(
            model_name='budtendercall',
            index=models.Index(fields=['created_at'], name='kiosk_budte_created_55d424_idx'),
        ),
        migrations.AddIndex(
            model_name='budtendercall',
            index=models.Index(fields=['kiosk_id'], name='kiosk_budte_kiosk_i_2b89b8_idx'),
        ),
    ]
