# Generated by Django 4.2 on 2025-06-11 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0006_budtendercall_budtendercalllog_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budtendercalllog',
            name='call',
        ),
        migrations.DeleteModel(
            name='BudtenderCall',
        ),
        migrations.DeleteModel(
            name='BudtenderCallLog',
        ),
    ]
