# Generated by Django 4.2.23 on 2025-06-22 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0007_remove_budtender_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='age_verified_at',
            field=models.DateTimeField(blank=True, help_text='When age was verified for this order', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_birthdate',
            field=models.DateField(blank=True, help_text="Customer's date of birth for age verification", null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_contact',
            field=models.CharField(blank=True, help_text="Customer's phone number or email (optional)", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_name',
            field=models.CharField(blank=True, help_text="Customer's full name from age verification", max_length=100, null=True),
        ),
    ]
