# Generated by Django 4.2.23 on 2025-06-22 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0008_order_age_verified_at_order_customer_birthdate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(help_text='Session ID of the customer', max_length=40)),
                ('customer_name', models.CharField(blank=True, help_text='Customer name if available', max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved')], default='pending', max_length=20)),
                ('message', models.TextField(blank=True, help_text='Optional message from customer')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_by', models.CharField(blank=True, help_text='Staff member who resolved', max_length=100)),
                ('order', models.ForeignKey(blank=True, help_text='Associated order if customer has items in cart', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistance_requests', to='kiosk.order')),
            ],
            options={
                'verbose_name': 'Assistance Request',
                'verbose_name_plural': 'Assistance Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
