# Generated by Django 4.2.23 on 2025-06-23 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0010_ordernotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialoffer',
            name='minimum_quantity',
            field=models.PositiveIntegerField(blank=True, help_text='Minimum quantity of this product needed for the discount to apply.', null=True),
        ),
        migrations.AddField(
            model_name='specialoffer',
            name='offer_display_text',
            field=models.CharField(blank=True, help_text="Custom text to display on product cards (e.g., 'Buy 3+ for 15% off!'). Leave blank to use default text.", max_length=200, null=True),
        ),
    ]
