# Generated by Django 4.2.23 on 2025-07-01 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0011_specialoffer_minimum_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.CharField(blank=True, help_text="Product weight (e.g., '3.5g', '1oz', '1/8th')", max_length=20, null=True),
        ),
    ]
