# Generated by Django 4.2.23 on 2025-07-15 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0012_product_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image2',
            field=models.ImageField(blank=True, help_text='Second product image for carousel', null=True, upload_to='products/'),
        ),
    ]
