# Generated by Django 4.2.23 on 2025-07-15 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0013_product_image2'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='legal_notice',
            field=models.TextField(blank=True, help_text='Legal notice or disclaimer for this product', null=True),
        ),
    ]
