# Generated by Django 4.2.23 on 2025-07-15 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0014_product_legal_notice'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(help_text="Field name (e.g., 'Height', 'Dimensions', 'Texture')", max_length=50)),
                ('field_value', models.CharField(help_text="Field value (e.g., '6 inches', '2x4x1 cm', 'Smooth')", max_length=200)),
                ('display_order', models.IntegerField(default=0, help_text='Order in which to display this field')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_fields', to='kiosk.product')),
            ],
            options={
                'ordering': ['display_order', 'field_name'],
                'unique_together': {('product', 'field_name')},
            },
        ),
    ]
